name: Canutin - CI

on: push

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node version
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - uses: actions/checkout@v1
      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Running tests
        run: yarn test
